# Generated by Django 5.2.4 on 2025-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-is_featured", "featured_order", "start_datetime", "name")
            },
        ),
        migrations.RemoveConstraint(
            model_name="eventticket",
            name="unique_active_ticket_per_user_event",
        ),
        migrations.AddField(
            model_name="event",
            name="featured_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers show earlier among featured events."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Featured events surface first in lists."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive events are hidden from users."
            ),
        ),
    ]
