# Generated by Django 5.2.4 on 2025-12-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Optional external payment link for this event.",
                max_length=500,
            ),
        ),
    ]
