# Generated by Django 5.2.4 on 2026-01-04 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_payment_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="eventticket",
            name="guest_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventticket",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
