# Generated by Django 5.2.4 on 2026-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventticket_guest_email_eventticket_guest_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="is_guest_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
