# Generated by Django 5.2.4 on 2025-11-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_user_avatar_url_user_full_name_user_is_social_login_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
