# Generated by Django 5.2.4 on 2025-12-01 16:51

import uuid

import django.db.models.deletion
import django_resized.forms
import storages.backends.s3
from django.db import migrations, models

import booking.upload


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("homepage", "0028_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cover_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=booking.upload.fitness_class_cover_upload_image_path,
                        verbose_name="Cover Image",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("yoga", "Yoga"),
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("open_gym", "Open Gym"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("default_duration_minutes", models.PositiveIntegerField(default=60)),
                ("capacity", models.PositiveIntegerField()),
                ("additional_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Trainers who can run this class",
                        related_name="fitness_classes",
                        to="homepage.trainer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("one_off", "One-off"),
                            ("weekly", "Weekly"),
                            ("multi_weekly", "Multiple days per week"),
                            ("daily", "Daily"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="List of weekday codes, e.g. ['mon', 'wed']",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("rrule", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fitness_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rules",
                        to="booking.fitnessclass",
                    ),
                ),
            ],
            options={
                "ordering": ("fitness_class__name", "start_date"),
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "capacity_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, overrides FitnessClass.capacity for this session.",
                        null=True,
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If set, overrides FitnessClass.base_price for this session.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fitness_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="booking.fitnessclass",
                    ),
                ),
                (
                    "created_from_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_sessions",
                        to="booking.recurrencerule",
                    ),
                ),
            ],
            options={
                "ordering": ("date", "start_time"),
            },
        ),
    ]
