# Generated by Django 5.2.4 on 2025-12-01 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_active_booking_per_session",
        ),
        migrations.AlterField(
            model_name="booking",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe PaymentIntent ID for PAYG bookings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "booked")),
                fields=("user", "class_session"),
                name="unique_active_booking_per_session",
            ),
        ),
    ]
