# Generated by Django 5.2.4 on 2025-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="attendance_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Not marked"),
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("no_show", "No-show"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("included", "Included in membership"),
                    ("pending", "Pending payment"),
                    ("paid", "Paid"),
                    ("void", "Voided/No payment due"),
                ],
                default="included",
                max_length=20,
            ),
        ),
    ]
