# Generated by Django 5.2.4 on 2025-12-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_attendance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessclass",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Optional external payment/booking link.",
                max_length=500,
            ),
        ),
    ]
