# Generated by Django 5.2.4 on 2026-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_remove_booking_unique_active_booking_per_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_guest_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
