# Generated by Codex on 2026-02-03

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_booking_is_guest_purchase"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_active_booking_per_session",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=Q(
                    ("status", "booked"),
                    ("user__isnull", False),
                    ("payment_status__in", ["included", "paid"]),
                ),
                fields=("user", "class_session"),
                name="unique_active_booking_per_session",
            ),
        ),
    ]
