# Generated by Django 5.2.4 on 2026-02-18 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0012_membershipreminderlog_and_membership_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermembership",
            name="starts_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
