# Generated by Django 5.2.4 on 2025-08-01 14:25

import django_resized.forms
import homepage.upload
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_slide_1', models.CharField(max_length=255, verbose_name='Title 1')),
                ('subtitle_slide_1', models.CharField(max_length=255, verbose_name='Subtitle 1')),
                ('title_slide_2', models.CharField(max_length=255, verbose_name='Title 2')),
                ('subtitle_slide_2', models.CharField(max_length=255, verbose_name='Subtitle 2')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[133, 40], upload_to=homepage.upload.homepage_logo_upload_image_path, verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('title_slide_1', 'created_at'),
            },
        ),
    ]
