# Generated by Django 5.2.4 on 2025-08-04 21:49

import django_resized.forms
import homepage.upload
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[133, 40], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.homepage_logo_upload_image_path, verbose_name='Logo')),
                ('img_slide_1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[1342, 768], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.homepage_slide1_upload_image_path, verbose_name='Image slide 1')),
                ('title_slide_1', models.TextField(verbose_name='Title 1')),
                ('subtitle_slide_1', models.TextField(verbose_name='Subtitle 1')),
                ('img_slide_2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1342, 768], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.homepage_slide2_upload_image_path, verbose_name='Image slide 2')),
                ('title_slide_2', models.TextField(blank=True, null=True, verbose_name='Title 2')),
                ('subtitle_slide_2', models.TextField(blank=True, null=True, verbose_name='Subtitle 2')),
                ('img_slide_3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1342, 768], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.homepage_slide3_upload_image_path, verbose_name='Image slide 3')),
                ('title_slide_3', models.TextField(blank=True, null=True, verbose_name='Title 3')),
                ('subtitle_slide_3', models.TextField(blank=True, null=True, verbose_name='Subtitle 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('title_slide_1', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Homepage', max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('banner', models.ManyToManyField(blank=True, to='homepage.banner')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
                'ordering': ('created_at',),
            },
        ),
    ]
