# Generated by Django 5.2.4 on 2025-08-05 16:01

import django_resized.forms
import storages.backends.s3
from django.db import migrations

import homepage.upload


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=90,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.homepage_logo_upload_image_path,
                verbose_name="Logo",
            ),
        ),
    ]
