# Generated by Django 5.2.4 on 2025-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle_slide_1',
            field=models.TextField(verbose_name='Subtitle 1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_slide_2',
            field=models.TextField(verbose_name='Subtitle 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_slide_1',
            field=models.TextField(verbose_name='Title 1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_slide_2',
            field=models.TextField(verbose_name='Title 2'),
        ),
    ]
