# Generated by Django 5.2.4 on 2025-08-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_banner_subtitle_slide_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_slide_3',
            field=models.TextField(default='test', verbose_name='Subtitle 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title_slide_3',
            field=models.TextField(default='test', verbose_name='Title 3'),
            preserve_default=False,
        ),
    ]
