# Generated by Django 5.2.4 on 2025-08-05 21:04

import django_resized.forms
import homepage.upload
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_banner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='About Us', max_length=255, verbose_name='Title')),
                ('homepage_display_header', models.TextField(verbose_name='Homepage Display Header')),
                ('homepage_display_text', models.TextField(verbose_name='Homepage Display Title')),
                ('highlight_text1', models.TextField(blank=True, null=True, verbose_name='Highlight 1')),
                ('highlight_text2', models.TextField(blank=True, null=True, verbose_name='Highlight 2')),
                ('highlight_text3', models.TextField(blank=True, null=True, verbose_name='Highlight 3')),
                ('about_us_homepage_image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.about_us_homepage_upload_image1_path, verbose_name='About Us Homepage Image 1')),
                ('about_us_homepage_image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[371, 421], upload_to=homepage.upload.about_us_homepage_upload_image2_path, verbose_name='About Us Homepage Image 2')),
                ('section_display_header', models.TextField(blank=True, null=True, verbose_name='Section Display Title')),
                ('section_display_text', models.TextField(blank=True, null=True, verbose_name='Section Display Text')),
                ('about_us_section_image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.about_us_section_upload_image1_path, verbose_name='About Us Homepage Image 1')),
                ('about_us_section_image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[371, 421], upload_to=homepage.upload.about_us_section_upload_image2_path, verbose_name='About Us Homepage Image 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
