# Generated by Django 5.2.4 on 2025-08-01 18:36

import django_resized.forms
import homepage.upload
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_banner_subtitle_slide_3_banner_title_slide_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img_slide_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1342, 768], upload_to=homepage.upload.homepage_logo_upload_image_path, verbose_name='Image slide 1'),
        ),
        migrations.AddField(
            model_name='banner',
            name='img_slide_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1342, 768], upload_to=homepage.upload.homepage_logo_upload_image_path, verbose_name='Image slide 2'),
        ),
        migrations.AddField(
            model_name='banner',
            name='img_slide_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1342, 768], upload_to=homepage.upload.homepage_logo_upload_image_path, verbose_name='Image slide 3'),
        ),
    ]
