# Generated by Django 5.2.4 on 2025-08-03 06:25

import django_resized.forms
import homepage.upload
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_banner_img_slide_1_banner_img_slide_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img_slide_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[1342, 768], upload_to=homepage.upload.homepage_logo_upload_image_path, verbose_name='Image slide 1'),
        ),
    ]
