# Generated by Django 5.2.4 on 2025-08-05 21:09

import django_resized.forms
import homepage.upload
import storages.backends.s3
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_aboutus_about_us_homepage_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_section_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[371, 421], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.about_us_section_upload_image2_path, verbose_name='About Us Section Image 2'),
        ),
    ]
