# Generated by Django 5.2.4 on 2025-08-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_banner_img_slide_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle_slide_2',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_slide_3',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle 3'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_slide_2',
            field=models.TextField(blank=True, null=True, verbose_name='Title 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_slide_3',
            field=models.TextField(blank=True, null=True, verbose_name='Title 3'),
        ),
    ]
