# Generated by Django 5.2.4 on 2025-08-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_aboutus_about_us_section_image2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('created_at',), 'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
