# Generated by Django 5.2.4 on 2025-08-03 21:44

import django_resized.forms
import homepage.upload
import storages.backends.s3
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_banner_img_slide_1_alter_banner_img_slide_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img_slide_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1342, 768], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.homepage_slide3_upload_image_path, verbose_name='Image slide 3'),
        ),
    ]
