# Generated by Django 5.2.4 on 2025-08-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0007_alter_aboutus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="homepage_display_text",
            field=models.TextField(verbose_name="Homepage Display Text"),
        ),
    ]
