# Generated by Django 5.2.4 on 2025-08-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0008_alter_aboutus_homepage_display_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_us",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.aboutus",
            ),
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="banner",
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.banner",
            ),
        ),
    ]
