# Generated by Django 5.2.4 on 2025-08-06 05:27

import django_resized.forms
import homepage.upload
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_homepage_about_us_remove_homepage_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.about_us_cover_upload_image_path, verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section_highlight_text1',
            field=models.TextField(blank=True, null=True, verbose_name='Section Highlight 1'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section_highlight_text2',
            field=models.TextField(blank=True, null=True, verbose_name='Section Highlight 2'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='section_highlight_text3',
            field=models.TextField(blank=True, null=True, verbose_name='Section Highlight 3'),
        ),
    ]
