# Generated by Django 5.2.4 on 2025-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0011_team_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="trainers",
            field=models.ManyToManyField(blank=True, null=True, to="homepage.trainer"),
        ),
    ]
