# Generated by Django 5.2.4 on 2025-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_team_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='homepage.trainer'),
        ),
    ]
