# Generated by Django 5.2.4 on 2025-08-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_team_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.team'),
        ),
    ]
