# Generated by Django 5.2.4 on 2025-08-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0015_homepage_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="team",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.team",
            ),
        ),
    ]
