# Generated by Django 5.2.4 on 2025-08-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_team_description_team_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='title',
            new_name='name',
        ),
    ]
