# Generated by Django 5.2.4 on 2025-08-06 20:27

import uuid

import django_resized.forms
import storages.backends.s3
from django.db import migrations, models

import homepage.upload


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0018_rename_title_trainer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cover_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.service_cover_upload_image_path,
                        verbose_name="Cover Image",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "short_description",
                    models.TextField(verbose_name="Short Description"),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Long Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("name", "created_at"),
            },
        ),
    ]
