# Generated by Django 5.2.4 on 2025-08-06 22:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0022_alter_homepage_service_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ's",
                "ordering": ("question", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="FAQ Description"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_title",
            field=models.CharField(
                default="Our Services", max_length=255, verbose_name="FAQ Title"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs",
            field=models.ManyToManyField(blank=True, to="homepage.faq"),
        ),
    ]
