# Generated by Django 5.2.4 on 2025-08-07 05:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0024_alter_homepage_faq_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("header", models.CharField(max_length=255, verbose_name="Header")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("phone", models.CharField(max_length=255, verbose_name="phone")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("email", models.CharField(max_length=255, verbose_name="Email")),
                ("social", models.CharField(max_length=255, verbose_name="Social")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ("header", "created_at"),
            },
        ),
    ]
