# Generated by Django 5.2.4 on 2025-08-07 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0025_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homepage.contact",
            ),
        ),
    ]
