# Generated by Django 5.2.4 on 2025-08-07 06:00

import django_resized.forms
import homepage.upload
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_homepage_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='access_key',
            field=models.CharField(default='23c5c285-578b-48cb-9ff9-643123da8e47', max_length=255, verbose_name='Access key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.contact_background_upload_image_path, verbose_name='Background Image'),
        ),
    ]
