# Generated by Django 5.2.4 on 2025-08-07 10:56

import django.db.models.deletion
import django_resized.forms
import homepage.upload
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_contact_access_key_contact_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], storage=storages.backends.s3.S3Storage(), upload_to=homepage.upload.footer_logo_upload_image_path, verbose_name='logo')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='Slogan')),
                ('instagram_link', models.CharField(max_length=255, verbose_name='Instagram Link')),
                ('tiktok_link', models.CharField(max_length=255, verbose_name='Tik Tok Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.contact')),
                ('services', models.ManyToManyField(blank=True, to='homepage.service')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
                'ordering': ('id', 'created_at'),
            },
        ),
    ]
