# Generated by Django 5.2.4 on 2025-12-29 23:09

import uuid

import django_resized.forms
import storages.backends.s3
from django.db import migrations, models

import homepage.upload


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0028_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "login_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_login_cover_upload_image_path,
                        verbose_name="login_cover",
                    ),
                ),
                (
                    "personal_area_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_personal_area_cover_upload_image_path,
                        verbose_name="personal_area_cover",
                    ),
                ),
                (
                    "main_events_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_main_events_cover_upload_image_path,
                        verbose_name="main_events_cover",
                    ),
                ),
                (
                    "main_classes_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_main_classes_cover_upload_image_path,
                        verbose_name="main_classes_cover",
                    ),
                ),
                (
                    "personal_tickets_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_personal_tickets_cover_upload_image_path,
                        verbose_name="personal_tickets_cover",
                    ),
                ),
                (
                    "personal_bookings_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_personal_bookings_cover_upload_image_path,
                        verbose_name="personal_bookings_logo",
                    ),
                ),
                (
                    "contact_us_cover",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1920, 1080],
                        storage=storages.backends.s3.S3Storage(),
                        upload_to=homepage.upload.assets_contact_us_cover_upload_image_path,
                        verbose_name="contact_us_cover",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Assets",
                "verbose_name_plural": "Assets",
                "ordering": ("id", "created_at"),
            },
        ),
    ]
