# Generated by Django 5.2.4 on 2025-12-29 23:15

import django_resized.forms
import storages.backends.s3
from django.db import migrations

import homepage.upload


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0029_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="contact_us_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_contact_us_cover_upload_image_path,
                verbose_name="Contact us cover",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="login_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_login_cover_upload_image_path,
                verbose_name="login cover",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="main_classes_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_main_classes_cover_upload_image_path,
                verbose_name="Main classes cover",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="main_events_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_main_events_cover_upload_image_path,
                verbose_name="Main events cover",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="personal_area_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_personal_area_cover_upload_image_path,
                verbose_name="Personal area cover",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="personal_bookings_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_personal_bookings_cover_upload_image_path,
                verbose_name="Personal bookings cover",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="personal_tickets_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_personal_tickets_cover_upload_image_path,
                verbose_name="Personal tickets cover",
            ),
        ),
    ]
