# Generated by Django 5.2.4 on 2026-01-08 17:44

import django_resized.forms
import storages.backends.s3
from django.db import migrations

import homepage.upload


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0030_alter_assets_contact_us_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="cancel_cover",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.assets_cancel_cover_upload_image_path,
                verbose_name="Cancel cover",
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="about_us_homepage_image2",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                storage=storages.backends.s3.S3Storage(),
                upload_to=homepage.upload.about_us_homepage_upload_image2_path,
                verbose_name="About Us Homepage Image 2",
            ),
        ),
    ]
