# Generated by Django 5.2.4 on 2026-01-23 09:19

from django.db import migrations, models

import homepage.models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0031_assets_cancel_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="google_key",
            field=models.CharField(
                default=homepage.models.get_google_oauth_client_id,
                max_length=255,
                verbose_name="Google key",
            ),
        ),
    ]
